In [3]:
import pandas as pd
import numpy as np

In [4]:
pd.__version__

'2.3.1'

In [6]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-10-01 14:05:29--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv’

car_fuel_efficiency 100%[===================>] 853.70K  --.-KB/s    in 0.02s   

2025-10-01 14:05:31 (34.1 MB/s) - ‘car_fuel_efficiency.csv’ saved [874188/874188]



In [7]:
df = pd.read_csv('car_fuel_efficiency.csv')

In [10]:
len(df)

9704

In [18]:
df.fuel_type.nunique()

2

In [64]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [43]:
df[df['origin'] == 'Asia'].fuel_efficiency_mpg.max()

np.float64(25.96722204888372)

In [45]:
df.horsepower.describe()

count    8996.000000
mean      149.657292
std        29.879555
min        37.000000
25%       130.000000
50%       149.000000
75%       170.000000
max       271.000000
Name: horsepower, dtype: float64

In [57]:
df.horsepower.value_counts()

horsepower
152.0    142
145.0    141
151.0    134
148.0    130
141.0    130
        ... 
40.0       1
57.0       1
245.0      1
252.0      1
61.0       1
Name: count, Length: 192, dtype: int64

In [65]:
df['horsepower'] = df['horsepower'].fillna(152.0)

In [66]:
df.horsepower.describe()

count    9704.000000
mean      149.828215
std        28.775248
min        37.000000
25%       131.000000
50%       152.000000
75%       168.000000
max       271.000000
Name: horsepower, dtype: float64

In [74]:
df_asia = df_asia[['vehicle_weight','model_year']][:7]
X = df_asia.to_numpy()
X

array([[3413.43375861, 2003.        ],
       [3149.66493422, 2007.        ],
       [3079.03899737, 2018.        ],
       [2542.39240183, 2009.        ],
       [3460.87098999, 2009.        ],
       [2484.88398604, 2008.        ],
       [3006.54228722, 2012.        ]])

In [81]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [87]:
XTX = matrix_matrix_multiplication(X.T,X)

XTX_Inv = np.linalg.inv(XTX)
XTX_Inv

array([[ 1.12464107e-06, -1.68991495e-06],
       [-1.68991495e-06,  2.57468996e-06]])

In [85]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [91]:
XTy = X.T @ y
w = XTX_Inv @ XTy

In [92]:
w

array([0.07099685, 0.41931263])